language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "4.2"
 - "5.0"

# Use container-based Travis infrastructure.
sudo: false

addons:
  sauce_connect: true

env:
  global:
    - secure: "vz4Nbu5XZHFfgyK7JseZs0sN76UQXlHvPsfwOExWi/lnE0k49StVuONyoIJTwVuUn0QnICE0PyM6AgMmo6iNboQVs0L+04CpBlFIlOQW4pFwN8j9aDoaeWaL239fKDoyRt8Z4oL/Ta2JD/VVCjjGsoCQ6ykZjXW4nYEECJHP3RXiUhBwPdH6O+7E3cQVXw/kZhNDMrlu5bPEe8C6JL2VAhkqQWsK51v/SIc8rgFLz2iRu/QcVh4VwLVgmr8U58K0yBsKsLw2yR9KYD6sh6nJUxzvib59kf0+BF4kFc/WTGPITLLOb5iGtdCn+YU5IjxyRCRq3BbRzFQyAd5xMp9W9XjrVgN8LGizWNX8KmeTdKVPiwyq2EwC60r69+QNOHUVxEVtJ/zb9iF+5qqRSAnfFs2dLWD/GIrlNugJHJMBVlpFswT7zoDg3T5FJJzIyyAIp7svQm+q3lAt2jb1H/8I7xGWv25mrqkEEBOPLuBydcP6/+rdQUI8PXqsQuW2emMNf7v6r+sYW6MKerbkNTg0M7OPXZ79twtj7S68xJNUN2FmCeIr7PEA5/05MVomdIzMWM47VTn/460qe11yvjSgJnwZpVmO+ATwUlTUm6TWeCym8YxBafShfHxkLltCxe0mnXE2FxrZIX3AZmUB9tiAxe7KegRApexfBifaZpHhc4U="
    - secure: "SCxD19qsLCsOlVUXzGNPzAOc0czyp2m9SAzpTwoHSN6JHhH/t2e+/Pjh1PHuLRNSb6TSPGfT2g6mLCofnhLt73Enxf42WE4KR9+bMw0manKkHwH8uFvzTIK18l4AIEWEGq6jfjgkHUd+WQ/y3dWKFVzaVHmI/EAl5DX527lW3x6wkE14Fko2vVCjT8OWmVsa+XQtqU4RFGB36BtdMQM06Gb4bT6jl8cA/IndroFY1K4rVBMToBYP1BVgF0BCkVy7UpVUfHyondGYuFCTFTHJbafmgYUkxPQrC9DJIzkyBknkgDg5zzNvViYANLiPzxBijxE3DJgRShs4XxhvrLdqr2J0vn5sV+1OuWWaJ4dVq0J/47p10/JD+vFkjUTfLwwPU9y8MlfMDpxNphuaonz7/F1jb+dGjkvI40g2I8qGs4Tgw7C17rZS/kb17+1ambSYpwVlC6A0zaS+xtOROB5GeiIBea5tXxchH/GV2ZAjk4EK9sywVcfSj9gbFN6xHKN9D9SP271A98kehMwq8YM6Lk2gBdgdCXM136VMwbQx1s8DCJDorxTxYgL4/Xhy8iHTk+EepN+Fv8kQzgYCacKTOUaR2e7y43ZvpwF5ezu6DqVmzbtc61Fl104z55oUbidM5AjwITpL+xPnZ/j2I+d1RQhBNUSGLI8S9TTrE23kDfc="

  matrix:
    - TEST_LOADER=script-atomic-onload
    - TEST_LOADER=labjs
    - TEST_LOADER=jquery

script:
  - npm run test-ci
